twig:
    form_themes: ['bootstrap_4_layout.html.twig']
    default_path: '%kernel.project_dir%/templates'
    globals:
        # Few globals configuration
        app_global:
            name: '%env(APP_NAME)%'
            logo:
                default: '%env(APP_LOGO)%'
                dark: '%env(APP_LOGO_DARK)%'
                light: '%env(APP_LOGO_LIGHT)%'
            privacy_policy: '%env(APP_PRIVACY_POLICY)%'
            terms_conditions: '%env(APP_TERMS_CONDITIONS)%'
            support_email: '%env(APP_SUPPORT_EMAIL)%'