# Select image from https://hub.docker.com/_/php/
stages:
  - test
  - build

image: php:7.4

# Select what we should cache
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - vendor/

services:
  - mysql:5.7

variables:
  # Configure mysql service (https://hub.docker.com/_/mysql/)
  MYSQL_ROOT_PASSWORD: symfony

# We test PHP7 with MySQL, but we allow it to fail
test:
  image: php:7.4
  stage: test
  variables:
    APP_NAME: "Symfony Dashboard"
    KERNEL_CLASS: "App\\Kernel"
    APP_SECRET: "$ecretf0rt3st"
    SYMFONY_DEPRECATIONS_HELPER: "999999"
    PANTHER_APP_ENV: "panther"
    DATABASE_URL: "mysql://root:symfony@mysql:3306/symfony?serverVersion=5.7"
    GOOGLE_OAUTH2_CLIENT_ID: "xxxxxxxx"
    GOOGLE_OAUTH2_CLIENT_SECRET: "xxxxxxx"
  script:
    # Install git, the php image doesn't have installed
    - apt-get update -yqq
    - apt-get install git libzip-dev zip -yqq
    - pecl install xdebug
    - docker-php-ext-enable xdebug

    # Install mysql driver
    - docker-php-ext-install pdo_mysql zip

    # Install composer
    - curl --show-error --silent https://getcomposer.org/installer | php

    # Install all project dependencies
    - php composer.phar install

    # Run PHPUnit
    - ./bin/phpunit --configuration phpunit.xml.dist --coverage-text --colors=never
  coverage: '/^\s*Lines:\s*\d+.\d+\%/'
  allow_failure: true

build:
  image: docker:19.03.1
  stage: build
  services:
    - docker:19.03.1-dind
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_TAG -f ./docker/web_app/Dockerfile .
    - docker push $IMAGE_TAG