services:
  mailer.dev.set_recipients:
    class: Symfony\Component\Mailer\EventListener\EnvelopeListener
    tags: ['kernel.event_subscriber']
    arguments:
      $sender: null  # Default sender. user@example.com
      $recipients: null  # Always BCC these address ['user@example.com']