name: CI

on:
  push:
    branches: [ github-actions ]
  pull_request:
    branches: [ github-actions ]

jobs:
  tests:

    runs-on: self-hosted

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: symfony
          MYSQL_DATABASE: symfony
          MYSQL_USER: symfony
          MYSQL_PASSWORD: symfony

    env:
      APP_NAME: "Symfony Dashboard"
      KERNEL_CLASS: "App\\Kernel"
      APP_SECRET: "$ecretf0rt3st"
      SYMFONY_DEPRECATIONS_HELPER: "999999"
      PANTHER_APP_ENV: "panther"
      DATABASE_URL: "mysql://symfony:symfony@mysql:3306/symfony?serverVersion=5.7"
      GOOGLE_OAUTH2_CLIENT_ID: "xxxxxxxx"
      GOOGLE_OAUTH2_CLIENT_SECRET: "xxxxxxx"

    container: php:7.4-cli-alpine

    steps:
      - uses: actions/checkout@v2
      - name: Install related libraries for alpine docker image
        run: |
          apk add --no-cache --update --virtual .phpize-deps $PHPIZE_DEPS
          apk add git libintl icu icu-dev
          pecl install xdebug
          docker-php-ext-enable xdebug
          docker-php-ext-configure intl --enable-intl
          docker-php-ext-install pdo pdo_mysql intl
          rm -rf /usr/share/php
          rm -rf /tmp/*
          apk del  .phpize-deps
      - name: Install composer executable
        run: curl --show-error --silent https://getcomposer.org/installer | php
      - name: Install project dependencies
        run: php composer.phar install
      - name: Run PHPUnit tests
        run: ./bin/phpunit --configuration phpunit.xml.dist --coverage-text --colors=never