name: CI

on:
  push:
    branches: [ github-actions ]
  pull_request:
    branches: [ github-actions ]

jobs:
  laravel-tests:

    runs-on: self-hosted

    steps:
      - name: My first step
        uses: docker://php:7.4-cli-alpine
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: vendor/bin/phpunit